name: state_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
